// react_app/src/components/DeceasedView/CondolencesPanel.tsx
import useFxn from '@/utils/useFunctions';

const CondolencesPanel = ({ condolences }: { condolences: any[] }) => {
    return (
        <div>
            {condolences && condolences.length > 0 ? (
                <ul className="list-group list-group-flush">
                     {condolences.map((condo, index) => (
                        <li key={index} className="list-group-item bg-transparent fst-italic pe-lg-5">
                            <div> "{condo.condolence}" </div>
                            <div>
                                <i className="bi bi-dash"></i>
                                <span>
                                    <span className="fw-bolder">{condo.condo_name}</span>
                                    <span className="fw-normal ms-1"> {condo.relationship ? `(${condo.relationship})` : ''}</span>
                                    <span className="small text-muted float-end">{condo.created_at ? useFxn.dateDisplay(condo.created_at) : ''}</span> 
                                    {/* Note: Vue code used condo.created, verify API response field name. Assuming created_at or created */}
                                </span>
                            </div>
                        </li>
                     ))}
                </ul>
            ) : (
                <div className="fst-italic">
                    No Condolences, click on the <b>icon: </b> <i className="bi bi-pencil small"></i> to add yours.
                </div>
            )}
        </div>
    );
};

export default CondolencesPanel;

// condo_frontend/src/components/DeceasedView/CondolencesPanel.vue
<template>
    <div v-if="condolences && condolences.length" class="">
        <ul class="list-group list-group-flush">
            <li v-for="condo in condolences" :key="condo" class="list-group-item bg-transparent fst-italic">
                <div> "{{ condo.condolence }}" </div>
                <div>
                    <i class="bi bi-dash"></i>
                    <span>
                        <span class="fw-bolder">{{ condo.condo_name }}</span>
                        <span class="fw-normal ms-1"> {{ condo.relationship ? '(' + condo.relationship + ')' : '' }}</span>
                        <span class="small text-muted float-end">{{ condo.created }}</span>
                    </span>
                </div>
            </li>
        </ul>
    </div>
    <div v-else class="fst-italic">
        No Condolences, click on the <b>icon: </b> <i class="bi bi-pencil small"></i> to add yours.
    </div>
</template>

<script setup lang="ts">
defineProps(['condolences'])
</script>
