// react_app/src/components/admin/HeaderAndMenu.tsx
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuthStore } from '@/store/useAuthStore';
import { useAppStore } from '@/store/useAppStore';
import ThemeToggler from '@/components/ThemeToggler';
import api from '@/api';
import { Dropdown } from 'react-bootstrap';

const HeaderAndMenu = () => {
    const { appName } = useAppStore();
    const { profileData, logout: storeLogout } = useAuthStore();
    const navigate = useNavigate();
    const location = useLocation();

    // Route name mapping (simplified)
    const getRouteName = () => {
        const path = location.pathname;
        if (path.includes('dashboard')) return 'Dashboard';
        if (path.includes('profile')) return 'Profile';
        return 'Admin';
    };

    const handleLogout = async () => {
        try {
            await api.userLogout();
        } catch (error) {
            // ignore
        }
        storeLogout();
        navigate('/login', { replace: true });
    };

    return (
        <nav className="navbar sticky-top navbar-light text-muted bg-secondary-subtle shadow-sm">
            <div className="container">
                <div className="py-2">
                    <span className="theme-color fw-bolder">{appName}</span>
                    &nbsp;| {getRouteName()}
                </div>
                <div className="d-flex gap-4">
                    <span>
                        <ThemeToggler />
                    </span>
                    <Dropdown className="d-none d-md-block">
                        <Dropdown.Toggle as="span" className="cursor-pointer" id="dropdown-custom-components">
                             <i className="bi bi-person-circle text-muted"></i>
                        </Dropdown.Toggle>

                        <Dropdown.Menu align="end" className="pt-0 rounded-top-0">
                            <Dropdown.Item disabled>{profileData?.email ?? ''}</Dropdown.Item>
                            <Dropdown.Item onClick={handleLogout} className="text-danger">
                                <i className="bi bi-power"></i> Logout
                            </Dropdown.Item>
                        </Dropdown.Menu>
                    </Dropdown>
                </div>
            </div>
        </nav>
    );
};

export default HeaderAndMenu;

// condo_frontend/src/views/Admin/Components/headerAndMenu.vue
<template>
    <nav class="navbar sticky-top navbar-light text-muted bg-secondary-subtle shadow-sm">
        <div class="container">
            <!-- <div class="fs-5 cursor-pointer" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample"
                aria-controls="offcanvasExample">
                <i class="bi bi-list"></i> &nbsp;

            </div> -->
            <div class="py-2">
                <span class="theme-color fw-bolder">{{ appVar.appName }}</span>
                | {{ route.name }}
            </div>
            <div class="d-flex gap-4">
                <span>
                    <ThemeToggler />
                </span>
                <div class="dropdown open d-non d-md-block">
                    <span class=" dropdown-toggle" type="button" id="triggerId" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="bi bi-person-circle text-muted"></i>
                    </span>
                    <div class="dropdown-menu dropdown-menu-end pt-0 rounded-top-0" aria-labelledby="triggerId">
                        <span class="dropdown-item disabled">{{ authStore.profileData?.email ?? '' }}</span>
                        <span class="dropdown-item cursor-pointer text-danger bg-transparent" @click="logout">
                            <i class="bi bi-power"></i> Logout
                        </span>
                    </div>
                </div>
            </div>

        </div>
    </nav>


    <!-- <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header bg-light">
            <h5 class="offcanvas-title text-muted " id="offcanvasExampleLabel">
                {{ authStore.profileData?.email ?? '' }}
            </h5>
            <button ref="offCanvasToggler" type="button" class="btn-close" data-bs-dismiss="offcanvas"
                aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <ul class="list-group list-group-flush mt-5">
                <li class="list-group-item">
                    <router-link to="/dashboard">
                        <i class="bi bi-columns-gap me-2"></i> Dashboard
                    </router-link>
                </li>

                <li class="list-group-item">
                    <router-link to="/profile">
                        <i class="bi bi-person me-2"></i> Profile
                    </router-link>
                </li>

                <div class="list-group-item mt-5 cursor-pointer" @click="logout">
                    <i class="bi bi-box-arrow-left"></i> Logout
                </div>
            </ul>

        </div>
    </div> -->
</template>

<script lang="ts" setup>
import { ref, watch } from 'vue';
import { useAuthStore } from '@/stores/authStore';
import { useAppVariables } from '@/stores/appVariables';
import { useRoute, useRouter } from 'vue-router';
import api from '@/stores/Helpers/axios'
import ThemeToggler from '@/components/themeToggler.vue';

const offCanvasToggler = ref<any>(null)

const authStore = useAuthStore()
const appVar = useAppVariables()
const route = useRoute()
const router = useRouter()


async function logout() {
    try {
        await api.userLogout()
    } catch (error) {

    }
    authStore.logout()
    router.replace({ name: 'Login' })
}

watch(() => route.path, () => {
    offCanvasToggler.value.click()
})
</script>


<style scoped>
/* @media (max-width: 797px) { */
.offcanvas {
    width: 300px;
}

/* } */

.list-group-item {
    border: 0px;
}

.list-group-item a {
    text-decoration: none;
    color: #8f8080;
}

.list-group-item a:hover {
    color: #000;
}

.active {
    color: #000 !important;
    font-weight: bold;
}
</style>
