// condo_frontend/src/components/condoBtn.vue
<template>
    <div class="fixed-bottom-btn animate__animated animate__heartBeat animate__delay-3s">
        <div @click="appVar.toggleCondoModal()" class="justify-content-end floatPanel">
            <div class="card btnCard shadow">
                <div><i class="bi bi-pencil"></i></div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { useAppVariables } from '@/stores/appVariables';
const appVar = useAppVariables()
</script>

<style scoped>
.fixed-bottom-btn {
    position: fixed;
    bottom: 0;
    right: 0;
    z-index: 999;
}


.floatPanel {
    margin-bottom: 60px;
    padding-right: 24px;
    display: flex;
    z-index: 999;
    position: relative;
    transition: all ease-in-out 0.4s;
    font-size: 11px;
}

.btnCard {
    width: 55px;
    height: 55px;
    border-radius: 50%;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 1.43rem;
    color: #fff;
    background-color: var(--theme-color);
    cursor: pointer;
}

@media (min-width: 979px) {
    .floatPanel {
        margin-bottom: 250px;
    }
}
</style>

// react_app/src/components/CondoBtn.tsx
import { useAppStore } from '@/store/useAppStore';

const CondoBtn = () => {
    const { toggleCondoModal } = useAppStore();

    return (
        <div className="fixed-bottom-btn animate__animated animate__heartBeat animate__delay-3s" style={{ position: 'fixed', bottom: 0, right: 0, zIndex: 999 }}>
            <div onClick={toggleCondoModal} className="justify-content-end floatPanel" style={{ marginBottom: '60px', paddingRight: '24px', display: 'flex', zIndex: 999, position: 'relative', transition: 'all ease-in-out 0.4s', fontSize: '11px', cursor: 'pointer' }}>
                <div className="card btnCard shadow" style={{ width: '55px', height: '55px', borderRadius: '50%', display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: '1.43rem', color: '#fff', backgroundColor: 'var(--theme-color)' }}>
                    <div><i className="bi bi-pencil"></i></div>
                </div>
            </div>
        </div>
    );
};

export default CondoBtn;
