// react_app/src/components/Header.tsx
import { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useAppStore } from '@/store/useAppStore';
import ThemeToggler from '@/components/ThemeToggler';
import SearchDeceasedModal from '@/components/modals/SearchDeceasedModal';

const Header = () => {
    const { toggleSearchModal } = useAppStore();
    const location = useLocation();
    
    // Scroll handling
    const [scrollY, setScrollY] = useState(0);

    useEffect(() => {
        const handleScroll = () => {
            setScrollY(window.scrollY);
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    const customClass = scrollY > 50 
        ? 'animate__animated animate__slideInDown animate__faster bg-white shadow-sm' 
        : '';

    // Active link helper
    const isActive = (path: string) => location.pathname === path ? 'active' : '';

    return (
        <>
            <nav className={`navbar navbar-expand-sm navbar-light fixed-top ${customClass}`}>
                <div className="container">
                    <Link className="navbar-brand" to="/" style={{ fontWeight: 700 }}>
                        <img src="/og-image.png" width="30" alt="" />
                    </Link>
                    {/* Toggler button omitted in Vue code, so omitting here too */}
                    
                    <div className="collapse navbar-collapse" id="collapsibleNavId" style={{ display: 'flex !important' /* Force display if bootstrap collapse hides it improperly without js toggler */ }}> 
                         {/* Note: The vue code uses bootstrap collapse classes but commented out the toggler button. 
                             It seems it expects desktop view mostly or relying on css. 
                             Vue code: <div className="collapse navbar-collapse" id="collapsibleNavId">. 
                             I'll assume bootstrap js handles the collapse class if toggler existed, 
                             but here it is always visible on desktop? 
                             The vue code has `d-lg-none` on the commented toggler.
                             I'll just stick to standard bootstrap.
                         */}
                        <ul className="navbar-nav me-auto mt-2 mt-lg-0">
                            <li className="nav-item">
                                <Link className={`nav-link ${isActive('/')}`} to="/">Home</Link>
                            </li>
                            <li className="nav-item">
                                <Link className={`nav-link text-dark ${isActive('/login')}`} to="/login">Login</Link>
                            </li>
                        </ul>
                        <span className="mx-4">
                            <ThemeToggler />
                        </span>
                        <div onClick={toggleSearchModal} className="cursor-pointer d-none d-md-block">
                            <i className="bi bi-search fs-5"></i>
                        </div>
                    </div>
                </div>
            </nav>
            <SearchDeceasedModal />
        </>
    );
};

export default Header;

// condo_frontend/src/components/Header.vue
<template>
    <nav class="navbar navbar-expand-sm navbar-light fixed-top" :class="customClass">
        <div class="container">
            <router-link class="navbar-brand" to="/" style="font-weight: 700;">
                <img src="/og-image.png" width="30" alt="">
            </router-link>
            <!-- <button class="navbar-toggler d-lg-none border-0" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button> -->
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <router-link class="nav-link" to="/">Home</router-link>
                    </li>
                    <li class="nav-item">
                        <router-link class="nav-link text-dark" to="/login">Login</router-link>
                    </li>
                </ul>
                <span class="mx-4">
                    <themeToggler />
                </span>
                <div @click="appVar.toggleSearchModal" class="cursor-pointer d-none d-md-block">
                    <i class="bi bi-search fs-5"></i>
                </div>
            </div>
        </div>
    </nav>
    <!-- search modal -->
    <SearchDeceasedModal />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useAppVariables } from '@/stores/appVariables';
import themeToggler from '@/components/themeToggler.vue'

const appVar = useAppVariables()

const customClass = computed(() => ({
    'animate__animated animate__slideInDown animate__faster': appVar.y_axis > 50,
    'bg-white shadow-sm': appVar.y_axis > 50,
}))


</script>

<style scoped>
.active {
    color: var(--theme-color) !important;
}
</style>
