// react_app/src/components/ThemeToggler.tsx
import { useAppStore } from '@/store/useAppStore';

const ThemeToggler = () => {
    const { appTheme, toggleTheme } = useAppStore();

    return (
        <span onClick={toggleTheme} className="cursor-pointer">
            {appTheme === 'dark' ? (
                <i className="bi bi-sun"></i>
            ) : (
                <i className="bi bi-moon"></i>
            )}
        </span>
    );
};

export default ThemeToggler;

// condo_frontend/src/components/themeToggler.vue
<template>
    <span @click="appVar.toggleTheme" class="cursor-pointer">
        <i v-if="appVar.appTheme == 'dark'" class="bi bi-sun"></i>
        <i v-else class="bi bi-moon"></i>
    </span>

</template>
<script setup lang="ts">
import { useAppVariables } from '@/stores/appVariables';
const appVar = useAppVariables()
</script>
