// condo_frontend/src/components/modals/imageViewModal.vue
<template>
    <div>
        <!-- Modal trigger button -->
        <button ref="openModal_image" class="btn d-none" data-bs-toggle="modal" data-bs-target="#imageModal">
        </button>

        <div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="modalTitleId"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-heade p-3  bg-theme border-0">
                        <h5 class="modal-title text-white fw-bold text-center">{{ appVar.appName }}.</h5>
                    </div>
                    <div class="modal-body rounded-0">
                        <img :src="appVar.currentImageToShow.url" class="img-fluid rounded-top" alt="" />
                        <p>
                            {{ appVar.currentImageToShow.caption }}
                        </p>
                    </div>
                    <div class="modal-footer border-0">
                        <button ref="closeModal_image" type="button" class="btn" data-bs-dismiss="modal">
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useAppVariables } from '@/stores/appVariables';
import { onBeforeRouteLeave } from 'vue-router';
import useFxn from '@/stores/Helpers/useFunctions';

const appVar = useAppVariables()
const openModal_image = ref<any>(null)
const closeModal_image = ref<any>(null)


watch(() => appVar.imageModal, () => {
    openModal_image.value.click()
});

onBeforeRouteLeave(() => {
    closeModal_image.value.click()
});
</script>

<style  scoped>
.modal.fade .modal-dialog {
    transform: scale(0.8);
    transition: transform 0.3s ease-out;
}

.modal.show .modal-dialog {
    transform: scale(1);
}
</style>

// react_app/src/components/modals/ImageViewModal.tsx
import { Modal } from 'react-bootstrap';
import { useAppStore } from '@/store/useAppStore';

const ImageViewModal = () => {
    const { imageModal, toggleImageModal, currentImageToShow } = useAppStore();

    const handleClose = () => {
        if (imageModal) toggleImageModal();
    };

    return (
        <Modal show={imageModal} onHide={handleClose} centered size="lg" className="bg-transparent border-0">
            <Modal.Body className="p-0 bg-transparent text-center position-relative">
                {currentImageToShow && (
                    <>
                         <button 
                            onClick={handleClose}
                            type="button" 
                            className="btn-close btn-close-white position-absolute top-0 end-0 m-3 z-3" 
                            aria-label="Close" 
                            style={{ filter: 'invert(1) grayscale(100%) brightness(200%)' }} // Make close button white if needed
                        ></button>
                        <img src={currentImageToShow.url} alt="Large View" className="img-fluid rounded shadow" style={{ maxHeight: '90vh' }} />
                        {currentImageToShow.caption && <div className="text-white mt-2">{currentImageToShow.caption}</div>}
                    </>
                )}
            </Modal.Body>
        </Modal>
    );
};

export default ImageViewModal;
