// condo_frontend/src/views/Admin/Dashboard.vue
<template>
    <div class="container mt-5 animate__animated animate__fadeIn">
        <div class="min-vh-100">

            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li v-for="tab in tabs" :key="tab.value" class="nav-item" role="presentation">
                    <button v-if="tab.adminAccess.includes(authStore.profileData.level.toString())"
                        @click="tabToShow = tab.value" :class="['nav-link', { active: tabToShow === tab.value }]"
                        type="button" role="tab" :aria-selected="tabToShow === tab.value"
                        :aria-controls="`tab-${tab.value}`">
                        {{ tab.name }}
                    </button>
                </li>
            </ul>

            <div class="tab-content">
                <div v-for="tab in tabs" :key="tab.value" :class="['tab-pane', { active: tabToShow === tab.value }]"
                    role="tabpanel" :id="`tab-${tab.value}`">
                    <component @done="tabToShow = 'history'" v-if="tabToShow === tab.value" :is="tab.component" />
                </div>
            </div>

        </div>
    </div>
    <deceasedLinkModal />
</template>

<script lang="ts" setup>
import { defineAsyncComponent, ref, onMounted } from 'vue';
import deceasedLinkModal from '@/components/modals/deceasedLinkModal.vue';
import { useAuthStore } from '@/stores/authStore';
import deceadedPostingTab from './tabContents/deceadedPostingTab.vue';

type Tabtypes = 'history' | 'new_post' | 'settings' | 'users'
type AsyncComponent = ReturnType<typeof defineAsyncComponent>;

const tabToShow = ref<Tabtypes>('new_post')
const authStore = useAuthStore()

const historyTab = defineAsyncComponent(() => import('./tabContents/historyTab.vue'));
const usersTab = defineAsyncComponent(() => import('./tabContents/usersTab.vue'));
// const settingsTab = defineAsyncComponent(() => import('./tabContents/settingsTab.vue'));

const tabs: { name: string, value: Tabtypes, component: AsyncComponent, adminAccess: string[] }[] = [
    { name: 'Post Memorial', value: 'new_post', component: deceadedPostingTab, adminAccess: ['1', '2'] },
    { name: 'Uploads History', value: 'history', component: historyTab, adminAccess: ['1', '2'] },
    { name: 'Users', value: 'users', component: usersTab, adminAccess: ['1'] },
    // { name: 'Settings', value: 'settings', component: settingsTab },
]

onMounted(() => {
    tabToShow.value = 'new_post'
})

</script>

<style scoped>
.nav-link,
.nav-item .active {
    border: none !important;
    background: transparent;
    color: inherit;
}

.nav-item {
    color: var(--bs-gray-600)
}

.nav-item .active {
    border-bottom: 1px solid var(--theme-color) !important;
    color: var(--theme-color) !important;
    background: transparent !important;
    font-weight: bolder;
}
</style>

// react_app/src/pages/admin/Dashboard.tsx
import { useState, useEffect } from 'react';
import { useAuthStore } from '@/store/useAuthStore';
import DeceasedPostingTab from './tabs/DeceasedPostingTab';
import HistoryTab from './tabs/HistoryTab';
import UsersTab from './tabs/UsersTab';

type TabTypes = 'history' | 'new_post' | 'users';

const Dashboard = () => {
    const [tabToShow, setTabToShow] = useState<TabTypes>('new_post');
    const { profileData } = useAuthStore();

    const tabs = [
        { name: 'Post Memorial', value: 'new_post', component: <DeceasedPostingTab onDone={() => setTabToShow('history')} />, adminAccess: ['1', '2'] },
        { name: 'Uploads History', value: 'history', component: <HistoryTab />, adminAccess: ['1', '2'] },
        { name: 'Users', value: 'users', component: <UsersTab />, adminAccess: ['1'] },
    ];

    useEffect(() => {
        setTabToShow('new_post');
    }, []);

    return (
        <div className="container mt-5 animate__animated animate__fadeIn">
             <div className="min-vh-100">
                <ul className="nav nav-tabs" id="myTab" role="tablist">
                    {tabs.map(tab => (
                        tab.adminAccess.includes(profileData?.level?.toString() || '') && (
                            <li key={tab.value} className="nav-item" role="presentation">
                                <button 
                                    className={`nav-link ${tabToShow === tab.value ? 'active' : ''}`}
                                    onClick={() => setTabToShow(tab.value as TabTypes)}
                                    type="button" 
                                    role="tab" 
                                    aria-selected={tabToShow === tab.value}
                                    style={{
                                        color: tabToShow === tab.value ? 'var(--theme-color)' : 'var(--bs-gray-600)',
                                        borderBottom: tabToShow === tab.value ? '1px solid var(--theme-color)' : 'none',
                                        fontWeight: tabToShow === tab.value ? 'bolder' : 'normal',
                                        background: 'transparent'
                                    }}
                                >
                                    {tab.name}
                                </button>
                            </li>
                        )
                    ))}
                </ul>

                <div className="tab-content">
                     {tabs.map(tab => (
                        <div key={tab.value} className={`tab-pane fade ${tabToShow === tab.value ? 'show active' : ''}`} role="tabpanel">
                            {tabToShow === tab.value && tab.component}
                        </div>
                     ))}
                </div>
             </div>
             {/* <deceasedLinkModal /> -- To be implemented */}
        </div>
    );
};

export default Dashboard;
